server:
  port: 0

spring:
  application:
    name: api-series
  data:
    mongodb:
      database: series-dev-mongo
      port: 27017
      host: localhost

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/