server:
  port: 8080
spring:
  application:
   name: api-series
  data:
    mongodb:
      database: series-dev-mongo
      port: 27017
      host: 44.201.102.47
springdoc:
  swagger-ui:
    path: /api/v1/series/swagger
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://44.203.152.200:8761/eureka
