server:
  port: 8080

spring:
  application:
   name: api-movie
  data:
    mongodb:
      host: 44.201.102.47
      port: 27017
      database: movies-dev-mongo
      username: grupo01
      password: Wn6np6A@6qiP

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://44.203.152.200:8761/eureka
