server:
  port: 8080

spring:
  application:
   name: api-series
  data:
    mongodb:
      database: series-dev-mongo
      port: 27017
      host: 44.201.102.47

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://44.203.152.200:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: serviceregistry,health,info