server:
  port: 8080

spring:
  application:
    name: api-movie
  data:
    mongodb:
      uri: mongodb://root:root1234@44.201.102.47:27017
      database: movies-dev-mongo

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://44.203.152.200:8761/eureka
