server:
  port: 8081
spring:
  application:
   name: api-series
  data:
    mongodb:
      uri: mongodb://root:root1234@44.201.102.47:27017
      database: series-dev-mongo
springdoc:
  swagger-ui:
    path: /api/v1/series/swagger
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://44.203.152.200:8761/eureka
