server:
  port: ${PORT:8761}

spring:
  application:

eureka:
  instance:
    hostname: 44.203.152.200
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
