server:
  port: 8761

spring:
  application:
   name: ms-eureka-server

eureka:
  instance:
    hostname: 44.203.152.200
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://44.203.152.200:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: serviceregistry,health,info