server:
  port: 8080

spring:
  application:
   name: ms-gateway-server
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - AddResponseHeader=Access-Control-Allow-Origin, *
      discovery:
        locator:
          enabled: true
      routes:
        - id: api-movie
          uri: lb://api-movie
          predicates:
            - Path=/api/v1/movies/**
            - Method=GET
        - id: api-movie-admin
          uri: lb://api-movie
          predicates:
            - Path=/api/v1/movies/**
            - Method=POST,PUT,DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter=ROLE_ADMIN WRITE DELETE
        - id: api-series
          uri: lb://api-series
          predicates:
            - Path=/api/v1/series/**
        - id: users-signup
          uri: lb://users
          predicates:
            - Path=/users/signup
        - id: users-login
          uri: lb://users
          predicates:
            - Path=/users/login
        - id: users-confirmation
          uri: lb://users
          predicates:
            - Path=/users/*/confirm
        - id: users-authorization
          uri: lb://users
          predicates:
            - Path=/users/**
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "*"

info:
  app:
    name: ${spring.application.name}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    service-url:
      defaultZone: http://44.203.152.200:8761/eureka

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway,serviceregistry,health,info

token:
  secret: UhQbrtfsX8Q0S6MoJFjzQZthOK4Kbd5h7gH6YtT3jKreEjICe9OdpUULUaG50mbM
