server:
  port: 8080

spring:
  application:
   name: ms-gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: api-movie
          uri: lb://api-movie
          predicates:
            - Path=/api/v1/movies/**
        - id: api-series
          uri: lb://api-series
          predicates:
            - Path=/api/v1/series/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE


info:
  app:
    name: ${spring.application.name}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    service-url:
      defaultZone: http://44.203.152.200:8761/eureka

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway,serviceregistry,health,info