server:
  port: 8082

spring:
  application:
    name: users
  devtools:
    restart:
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://44.203.152.200:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: always
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    instances:
      movies:
        failure-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 10s
        sliding-window-type: COUNT_BASED
        sliding-window-size: 2
        minimum-number-of-calls: 1
        event-consumer-buffer-size: 10
  retry:
    retry-aspect-order: 2
    instances:
      movies:
        max-attempts: 3
        wait-duration: 2s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 5

logging:
  level:
    com.ecran.api.users.data.MoviesServiceClient: DEBUG
    com.ecran.api.users.service.UsersServiceImpl: DEBUG
  pattern:
    level: "%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]"
  file:
    name: users.log